### ISSUE TITLE
Looks like one dependency is failing to build on node v12.4.0

### ISSUE THREAD

**Issue by jloveric** [WebReflection/flatted#23]
$ npm add flatted

> fsevents@1.2.4 install.../node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@12.4.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:50:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> exports);

**Comment by WebReflection** [comment]
this module has no dependencies
